### ISSUE TITLE
Rework decent.im site

### ISSUE THREAD

**Issue by andrey-utkin** [decent-im/decent.im#23]
Github's interpreter of markdown templated pages seems to break the site on addition of post, supposedly this is an issue with third-side theme I've built the site on.

Ways to go:

* investigate the breakage and fix the theme, proceed using github's templates engine
* switch to any another markdown-based static site generator, e.g. Pelican (Python-based), or some from miriad of Ruby-based ones
* hand-hack simplistic markdown pages
* redirect all pages to wiki hosted on github (we can export all data from there, right?)

Considerations:

* avoid lock-in with github (so that if it ever sinks, we don't)
* own all our data, keep autonomous copies of content sources
* minimize maintenance hassle
* support editing pages and adding news posts

**Comment by nathalier** [comment]
All existing pages were migrated to Cactus static site generator.
Pushed to https://github.com/decent-im/website
Can be tested on http://odessite.com.ua:8000

To do next:
- rework top post, separate it from blog records and put on home page
- set up rss feed for new blog page
- add logo

**Comment by andrey-utkin** [comment]
Deployed everywhere. Content and styling work will follow.

Thanks a lot Nathalie!
